services:
  - type: web
    name: user-service
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api_utilisateur
          property: connectionString
      - key: JWT_SECRET
        sync: false # configure dans Render
      - key: RABBITMQ_URL
        sync: false # configure dans Render
      - key: GOOGLE_CLIENT_ID
        sync: false # configure dans Render
      - key: GMAIL_USER
        sync: false # configure dans Render
      - key: GMAIL_PASS
        sync: false # configure dans Render
      - key: FRONTEND_URL
        value: http://localhost:5173
