openapi: 3.1.0
info:
  title: API Gestion des Utilisateurs - Plateforme Justicket
  version: 1.0.0
  description: >
    Cette API permet aux utilisateurs de s'inscrire, se connecter, 
    récupérer leur profil et gérer leur accès sur la plateforme Justicket.

servers:
  - url: https://api-utilisateur.onrender.com
    description: Serveur de développement

paths:
  /api/auth/signup:
    post:
      summary: Créer un compte utilisateur
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: "exemple@gmail.com"
                password:
                  type: string
                  example: "motdepass"
      responses:
        "201":
          description: Compte créé avec succès.
        "409":
          description: Email déjà utilisé.

  /api/auth/signin:
    post:
      summary: Se connecter à l'application
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: "exemple@gmail.com"
                password:
                  type: string
                  example: "motdepass"
      responses:
        "200":
          description: Connexion réussie.
        "401":
          description: Identifiants incorrects.

  /api/auth/google:
    post:
      summary: Connexion avec Google OAuth
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tokenId
              properties:
                token:
                  type: string
      responses:
        "200":
          description: Connexion réussie
        "400":
          description: Token Google invalide

  /api/auth/profile:
    get:
      summary: Obtenir les informations du profil
      tags:
        - Utilisateurs
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Informations de l'utilisateur.
        "403":
          description: Accès interdit.

  /api/auth/logout:
    post:
      summary: Déconnexion de l'utilisateur
      tags:
        - Authentification
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Déconnexion réussie.

  /api/auth/request-password-reset:
    post:
      summary: Demande de réinitialisation du mot de passe
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: "exemple@gmail.com"
      responses:
        "200":
          description: Email envoyé avec un lien de réinitialisation.
        "404":
          description: Adresse email introuvable.

  /api/auth/reset-password:
    post:
      summary: Modifier son mot de passe après une demande de réinitialisation
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
              properties:
                token:
                  type: string
                  example: "eyJhbGciOiJIUz..."
                newPassword:
                  type: string
                  example: "NouveauMostdpass"
      responses:
        "200":
          description: Mot de passe réinitialisé avec succès.
        "400":
          description: Token invalide ou expiré.

  /api/users:
    get:
      summary: Liste des utilisateurs interface admin
      tags:
        - Utilisateurs
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    email:
                      type: string
                    role:
                      type: string
        "403":
          description: Accès interdit

  /api/users/{id}:
    get:
      summary: Récupérer un utilisateur
      tags:
        - Utilisateurs
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Détails de l'utilisateur
        "404":
          description: Utilisateur non trouvé

    delete:
      summary: Suppression d’un utilisateur
      tags:
        - Utilisateurs
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Utilisateur supprimé
        "403":
          description: Accès interdit

  /api/users/{id}/role:
    patch:
      summary: Modifier le rôle d’un utilisateur
      tags:
        - Utilisateurs
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - role
              properties:
                role:
                  type: string
                  enum: [admin, buyer, anonym]
      responses:
        "200":
          description: Role mis à jour
        "403":
          description: Accès interdit
        "404":
          description: Utilisateur non trouvé

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
